name: MLOps-Serverless-CI

on:
  push:
    branches:
      - main

jobs:
  trigger-train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 1. Install the official Databricks CLI
      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      # 2. Run the Job using the CLI (Replace 123456789 with your Job ID)
      - name: Trigger Databricks Job
        run: |
          databricks jobs run-now 481984564547708
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}